// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBtn: typeof import('./components/VBtn.vue')['default']
    VCard: typeof import('./components/v-card.vue')['default']
    VCardContent: typeof import('./components/v-card-content.vue')['default']
    VCardHead: typeof import('./components/v-card-head.vue')['default']
    VCardTitle: typeof import('./components/v-card-title.vue')['default']
    VChart: typeof import('./components/v-chart.vue')['default']
    VCheckbox: typeof import('./components/v-checkbox.vue')['default']
    VCode: typeof import('./components/v-code.vue')['default']
    VContainer: typeof import('./components/v-container.vue')['default']
    VDialog: typeof import('./components/v-dialog.vue')['default']
    VDivider: typeof import('./components/v-divider.vue')['default']
    VDrawer: typeof import('./components/v-drawer.vue')['default']
    VForm: typeof import('./components/VForm.vue')['default']
    VGallery: typeof import('./components/v-gallery.vue')['default']
    VIcon: typeof import('./components/v-icon.vue')['default']
    VIconPicker: typeof import('./components/v-icon-picker.vue')['default']
    VInput: typeof import('./components/v-input.vue')['default']
    VLayout: typeof import('./components/v-layout.vue')['default']
    VLayoutContent: typeof import('./components/v-layout-content.vue')['default']
    VLayoutDrawer: typeof import('./components/v-layout-drawer.vue')['default']
    VLayoutToolbar: typeof import('./components/v-layout-toolbar.vue')['default']
    VLink: typeof import('./components/v-link.vue')['default']
    VListItem: typeof import('./components/v-list-item.vue')['default']
    VLogo: typeof import('./components/VLogo.vue')['default']
    VMenu: typeof import('./components/v-menu.vue')['default']
    VResizeLine: typeof import('./components/v-resize-line.vue')['default']
    VSelect: typeof import('./components/v-select.vue')['default']
    VTab: typeof import('./components/v-tab.vue')['default']
    VTabItem: typeof import('./components/v-tab-item.vue')['default']
    VTable: typeof import('./components/v-table.vue')['default']
    VTd: typeof import('./components/VTd.vue')['default']
    VTextarea: typeof import('./components/v-textarea.vue')['default']
    VTh: typeof import('./components/VTh.vue')['default']
    VTr: typeof import('./components/VTr.vue')['default']
  }
}
