/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBtn: typeof import('./components/VBtn.vue')['default']
    VCard: typeof import('./components/VCard.vue')['default']
    VCardContent: typeof import('./components/VCardContent.vue')['default']
    VCardHead: typeof import('./components/VCardHead.vue')['default']
    VCardTitle: typeof import('./components/VCardTitle.vue')['default']
    VChart: typeof import('./components/VChart.vue')['default']
    VCheckbox: typeof import('./components/VCheckbox.vue')['default']
    VCode: typeof import('./components/VCode.vue')['default']
    VContainer: typeof import('./components/VContainer.vue')['default']
    VDialog: typeof import('./components/VDialog.vue')['default']
    VDivider: typeof import('./components/VDivider.vue')['default']
    VDrawer: typeof import('./components/VDrawer.vue')['default']
    VForm: typeof import('./components/VForm.vue')['default']
    VGallery: typeof import('./components/VGallery.vue')['default']
    VIcon: typeof import('./components/VIcon.vue')['default']
    VIconPicker: typeof import('./components/VIconPicker.vue')['default']
    VInput: typeof import('./components/VInput.vue')['default']
    VLayout: typeof import('./components/VLayout.vue')['default']
    VLayoutContent: typeof import('./components/VLayoutContent.vue')['default']
    VLayoutDrawer: typeof import('./components/VLayoutDrawer.vue')['default']
    VLayoutToolbar: typeof import('./components/VLayoutToolbar.vue')['default']
    VLink: typeof import('./components/VLink.vue')['default']
    VListItem: typeof import('./components/VListItem.vue')['default']
    VLogo: typeof import('./components/VLogo.vue')['default']
    VMenu: typeof import('./components/VMenu.vue')['default']
    VResizeLine: typeof import('./components/VResizeLine.vue')['default']
    VSelect: typeof import('./components/VSelect.vue')['default']
    VTab: typeof import('./components/VTab.vue')['default']
    VTabItem: typeof import('./components/VTabItem.vue')['default']
    VTable: typeof import('./components/VTable.vue')['default']
    VTd: typeof import('./components/VTd.vue')['default']
    VTextarea: typeof import('./components/VTextarea.vue')['default']
    VTh: typeof import('./components/VTh.vue')['default']
    VTooltip: typeof import('./components/VTooltip.vue')['default']
    VTr: typeof import('./components/VTr.vue')['default']
  }
}
